<?php
/**
 * Created by PhpStorm.
 * User: mirekratman
 * Date: 10/07/15
 * Time: 12:58
 */

$url = 'http://rapi.modgen.net';
$db = ''; //DB name in Modgen environment
$key = '';  //Hash for DB name generated by modgen environment
